export const annotationList = [
    {
        label:'person',
        name:'人'
    },
    {
        label:'bicycle',
        name:'自行车'
    },
    {
        label:'car',
        name:'轿车'
    },
    {
        label:'motorcycle',
        name:'摩托车'
    },
    {
        label:'airplane',
        name:'飞机'
    },
    {
        label:'bus',
        name:'公交车'
    },
    {
        label:'train',
        name:'火车'
    },
    {
        label:'truck',
        name:'卡车'
    },
    {
        label:'boat',
        name:'船'
    },
    {
        label:'traffic light',
        name:'交通信号灯'
    },
    {
        label:'fire hydrant',
        name:'消防栓'
    },
    {
        label:'stop sign',
        name:'停车标志'
    },
    {
        label:'parking meter',
        name:'停车计时器'
    },
    {
        label:'bench',
        name:'长椅'
    },
    {
        label:'bird',
        name:'鸟'
    },
    {
        label:'cat',
        name:'猫'
    },
    {
        label:'dog',
        name:'狗'
    },
    {
        label:'horse',
        name:'马'
    },{
        label:'sheep',
        name:'羊'
    },
    {
        label:'cow',
        name:'牛'
    },
    {
        label:'elephant',
        name:'大象'
    },
    {
        label:'bear',
        name:'熊'
    },
    {
        label:'zebra',
        name:'斑马'
    },
    {
        label:'giraffe',
        name:'长颈鹿'
    },
    {
        label:'backpack',
        name:'背包'
    },
    {
        label:'umbrella',
        name:'雨伞'
    },
    {
        label:'handbag',
        name:'手提包'
    },
    {
        label:'tie',
        name:'领带'
    },
    {
        label:'suitcase',
        name:'行李箱'
    },
    {
        label:'frisbee',
        name:'飞盘'
    },
    {
        label:'skis',
        name:'滑雪板'
    },
    {
        label:'snowboard',
        name:'单板滑雪'
    },
    {
        label:'sports ball',
        name:'运动球'
    },
    {
        label:'kite',
        name:'风筝'
    },
    {
        label:'baseball bat',
        name:'棒球棒'
    },
    {
        label:'baseball glove',
        name:'棒球手套'
    },
    {
        label:'skateboard',
        name:'滑板'
    },
    {
        label:'surfboard',
        name:'冲浪板'
    },
    {
        label:'tennis racket',
        name:'网球拍'
    },
    {
        label:'bottle',
        name:'瓶子'
    },
    {
        label:'wine glass',
        name:'酒杯'
    },
    {
        label:'cup',
        name:'杯子'
    },
    {
        label:'fork',
        name:'叉子'
    },
    {
        label:'knife',
        name:'刀'
    },
    {
        label:'spoon',
        name:'勺子'
    },
    {
        label:'bowl',
        name:'碗'
    },
    {
        label:'banana',
        name:'香蕉'
    },
    {
        label:'apple',
        name:'苹果'
    },
    {
        label:'sandwich',
        name:'三明治'
    },
    {
        label:'orange',
        name:'橙子'
    },
    {
        label:'broccoli',
        name:'西兰花'
    },
    {
        label:'carrot',
        name:'胡萝卜'
    },
    {
        label:'hot dog',
        name:'热狗'
    },
    {
        label:'pizza',
        name:'披萨'
    },
    {
        label:'donut',
        name:'甜甜圈'
    },
    {
        label:'cake',
        name:'蛋糕'
    },
    {
        label:'chair',
        name:'椅子'
    },
    {
        label:'couch',
        name:'沙发'
    },
    {
        label:'potted plant',
        name:'盆栽植物'
    },
    {
        label:'bed',
        name:'床'
    },
    {
        label:'dining table',
        name:'餐桌'
    },
    {
        label:'toilet',
        name:'马桶'
    },
    {
        label:'tv',
        name:'电视'
    },
    {
        label:'laptop',
        name:'笔记本电脑'
    },
    {
        label:'mouse',
        name:'鼠标'
    },
    {
        label:'remote',
        name:'遥控器'
    },
    {
        label:'keyboard',
        name:'键盘'
    },
    {
        label:'cell phone',
        name:'手机'
    },
    {
        label:'microwave',
        name:'微波炉'
    },
    {
        label:'oven',
        name:'烤箱'
    },
    {
        label:'toaster',
        name:'烤面包机'
    },
    {
        label:'sink',
        name:'水槽'
    },
    {
        label:'refrigerator',
        name:'冰箱'
    },
    {
        label:'book',
        name:'书'
    },
    {
        label:'clock',
        name:'时钟'
    },
    {
        label:'vase',
        name:'花瓶'
    },
    {
        label:'scissors',
        name:'剪刀'
    },
    {
        label:'teddy bear',
        name:'泰迪熊'
    },
    {
        label:'hair drier',
        name:'吹风机'
    },
    {
        label:'toothbrush',
        name:'牙刷'
    },
    
]